title = "Mauritanienne d'Approvisionnement et de Services"
baseURL = "/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon.ico"
  logo = "images/mas_logo.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/alfredomartel"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  #featured_image = "images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 6



[languages]
[languages.en]
  title = "Mauritanienne d'Approvisionnement et de Services"
  weight = 1
  languageName = "English"
  contentDir = "content/en"

[languages.fr]
  title = "Mauritanienne d'Approvisionnement et de Services"
  weight = 2
  languageName = "Français"
  contentDir = "content/fr"

[languages.es]
  title = "Mauritanienne d'Approvisionnement et de Services"
  weight = 3
  languageName = "Español"
  contentDir = "content/es"

   